export const FETCH_EDUCATIONAL_DATA = "FETCH_EDUCATIONAL_DATA";
export const FETCH_EDUCATIONAL_DATA_SUCCESS = "FETCH_EDUCATIONAL_DATA_SUCCESS";
export const FETCH_EDUCATIONAL_DATA_FAILED = "FETCH_EDUCATIONAL_DATA_FAILED";
export const FETCH_ALL_TEACHERS = "FETCH_ALL_TEACHERS";
export const FETCH_ALL_TEACHERS_SUCCESS = "FETCH_ALL_TEACHERS_SUCCESS";
export const FETCH_ALL_TEACHERS_FAILED = "FETCH_ALL_TEACHERS_FAILED";
