export const FETCH_EDUCATIONAL_DATA = "FETCH_EDUCATIONAL_DATA";
export const FETCH_EDUCATIONAL_DATA_SUCCESS = "FETCH_EDUCATIONAL_DATA_SUCCESS";
export const FETCH_EDUCATIONAL_DATA_FAILED = "FETCH_EDUCATIONAL_DATA_FAILED";
