export const FETCH_EDUCATIONAL_DATA = "FETCH_EDUCATIONAL_DATA";
export const FETCH_EDUCATIONAL_DATA_SUCCESS = "FETCH_EDUCATIONAL_DATA_SUCCESS";
export const FETCH_EDUCATIONAL_DATA_FAILED = "FETCH_EDUCATIONAL_DATA_FAILED";
export const FETCH_ALL_TEACHERS = "FETCH_ALL_TEACHERS";
export const FETCH_ALL_TEACHERS_SUCCESS = "FETCH_ALL_TEACHERS_SUCCESS";
export const FETCH_ALL_TEACHERS_FAILED = "FETCH_ALL_TEACHERS_FAILED";
//Register user
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED";
//login User
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";
//get user
export const GET_USER = "GET_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_DATA_FAILED = "GET_USER_DATA_FAILED";
//Delete User Account
export const DELETE_USER_ACCOUNT = "DELETE_USER_ACCOUNT";
export const DELETE_USER_ACCOUNT_SUCCESS = "DELETE_USER_ACCOUNT";
export const DELETE_USER_ACCOUNT_FAILED = "DELETE_USER_ACCOUNT";
//Educational typ
export const Add_EDUCATION_DATA = "Add_EDUCATION_DATA";
export const Add_EDUCATION_DATA_SUCCESS = "Add_EDUCATION_DATA_SUCCESS";
export const Add_EDUCATION_DATA_FAILED = "Add_EDUCATION_DATA_FAILED";
export const DELETE_EDUCATION_DATA = "DELETE_EDUCATION_DATA";
export const DELETE_EDUCATION_DATA_SUCCESS = "DELETE_EDUCATION_DATA_SUCCESS";
export const DELETE_EDUCATION_DATA_FAILED = "DELETE_EDUCATION_DATA_FAILED";
//update courseDAta
export const UPDATE_COURSE_DATA = "UPDATE_COURSE_DATA";
export const UPDATE_COURSE_DATA_SUCCESS = "UPDATE_COURSE_DATA_SUCCESS";
export const UPDATE_COURSE_DATA_FAILED = "UPDATE_COURSE_DATA_FAILED";

export const FIND_DATA_BYID = "FIND_DATA_BYID";
export const FIND_DATA_BYID_SUCCESS = "FIND_DATA_BYID_SUCCESS";
export const FIND_DATA_BYID_FAILED = "FIND_DATA_BYID_FAILED";
